import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'tr' | 'en';
  setLanguage: (lang: 'tr' | 'en') => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  tr: {
    // Navigation
    'nav.home': 'Ana Sayfa',
    'nav.products': 'Ürünler',
    'nav.solutions': 'Çözümler',
    'nav.sectors': 'Sektörler',
    'nav.pricing': 'Fiyatlandırma',
    'nav.about': 'Hakkımızda',
    'nav.contact': 'İletişim',
    'nav.blog': 'Blog',
    'nav.documentation': 'Dokümantasyon',
    'nav.support': 'Destek',
    'nav.resources': 'Kaynaklar',
    'nav.small-business': 'Küçük İşletme',
    'nav.medium-business': 'Orta Ölçekli',
    'nav.enterprise': 'Kurumsal',
    'nav.custom-solutions': 'Özel Çözümler',
    'nav.free-demo': 'Ücretsiz Demo',
    
    // Pricing
    'pricing.small-business': 'Küçük İşletme',
    'pricing.medium-business': 'Orta Ölçekli',
    'pricing.enterprise': 'Kurumsal',
    
    // Small Business Page
    'small-business.title': 'Küçük İşletmeler için',
    'small-business.subtitle': 'Küçük işletmeler için özel tasarlanmış uygun fiyatlı yapay zeka çözümleri. Kolay kurulum, basit kullanım ve hızlı geri dönüş ile işinizi büyütün.',
    
    // Sectors
    'sectors.electronics': 'Elektronik',
    'sectors.automotive': 'Otomotiv',
    'sectors.food-beverage': 'Gıda & İçecek',
    'sectors.manufacturing': 'İmalat',
    'sectors.machinery': 'Makine',
    'sectors.pharmaceutical': 'İlaç',
    'sectors.textile': 'Tekstil',
    'sectors.energy': 'Enerji',
    
    // Solutions
    'solutions.mes-api': 'MES API',
    'solutions.image-api': 'Görüntü API',
    'solutions.process-monitoring': 'Süreç İzleme',
    'solutions.production-control': 'Üretim Kontrolü',
    'solutions.erp-integration': 'ERP Entegrasyonu',
    'solutions.sensor-analytics': 'Sensör Analizi',
    'solutions.custom-solutions': 'Özel Çözümler',
    
    // Hero Section
    'hero.title': 'Üretim Süreçlerinizi',
    'hero.title.highlight': 'Görüntü İşleme ile Optimize Edin',
    'hero.subtitle': 'MES (Manufacturing Execution System) çözümlerimizle üretim hatlarınızı gerçek zamanlı izleyin, kalite kontrolünü otomatikleştirin ve ERP sistemlerinizle entegre edin.',
    'hero.cta.demo': 'Ücretsiz Demo',
    'hero.cta.learn': 'Daha Fazla Bilgi',
    'hero.trusted': 'Türkiye\'nin önde gelen üretim şirketleri tarafından güveniliyor',
    
    // Features
    'features.title': 'MES Çözümlerimiz',
    'features.subtitle': 'Üretim süreçlerinizi optimize etmek için gelişmiş teknolojiler',
    'features.production.title': 'Üretim Planlama',
    'features.production.desc': 'İş emirleri, kaynak planlama ve üretim programlama',
    'features.quality.title': 'Kalite Yönetimi',
    'features.quality.desc': 'Görüntü işleme ile otomatik kalite kontrol',
    'features.process.title': 'Süreç İzleme',
    'features.process.desc': 'Gerçek zamanlı üretim süreçlerini izleme',
    'features.integration.title': 'ERP Entegrasyonu',
    'features.integration.desc': 'SAP, Oracle ve diğer ERP sistemleriyle entegrasyon',
    'features.analytics.title': 'Veri Analizi',
    'features.analytics.desc': 'Üretim verilerini analiz etme ve raporlama',
    'features.inventory.title': 'Stok Yönetimi',
    'features.inventory.desc': 'Hammadde ve yarı mamul stok takibi',
    
    // Dashboard
    'dashboard.title': 'MES Kontrol Paneli',
    'dashboard.subtitle': 'Üretim süreçlerinizi tek ekrandan yönetin',
    'dashboard.production-lines': 'Üretim Hatları',
    'dashboard.quality-metrics': 'Kalite Metrikleri',
    'dashboard.efficiency': 'Verimlilik',
    'dashboard.defect-rate': 'Hata Oranı',
    'dashboard.throughput': 'Üretim Hızı',
    'dashboard.oee': 'OEE Skoru',
    'dashboard.active-orders': 'Aktif Siparişler',
    'dashboard.completed-today': 'Bugün Tamamlanan',
    'dashboard.pending': 'Bekleyen',
    'dashboard.in-progress': 'Devam Eden',
    
    // Image Processing
    'image.title': 'Görüntü İşleme ile Kalite Kontrol',
    'image.subtitle': 'Yapay zeka destekli görüntü analizi ile üretim kalitesini artırın',
    'image.defect-detection': 'Hata Tespiti',
    'image.dimension-check': 'Boyut Kontrolü',
    'image.surface-analysis': 'Yüzey Analizi',
    'image.color-matching': 'Renk Eşleştirme',
    
    // Solutions Page
    'solutions.title': 'MES',
    'solutions.title.highlight': 'Çözümlerimiz',
    'solutions.subtitle': 'Üretim süreçlerinizi optimize etmek için kapsamlı MES modülleri',
    'solutions.explore-solution': 'Çözümü Keşfet',
    'solutions.success-stories': 'Başarı Hikayeleri',
    'solutions.customer-results': 'Müşterilerimizin elde ettiği sonuçlar',
    'solutions.accident-reduction': 'Kaza Azalması',
    'solutions.safety-compliance': 'Güvenlik Uyumu',
    'solutions.quality-increase': 'Kalite Artışı',
    'solutions.error-reduction': 'Hata Azalması',
    'solutions.efficiency': 'Verimlilik',
    'solutions.measurement-accuracy': 'Ölçüm Doğruluğu',
    'solutions.processing-speed': 'İşlem Hızı',
    'solutions.cost-savings': 'Maliyet Tasarrufu',
    'solutions.easy-integration': 'Kolay Entegrasyon',
    'solutions.works-seamlessly': 'Mevcut sistemlerinizle sorunsuz çalışır',
    'solutions.secure': 'Güvenli',
    'solutions.secure.desc': 'Kurumsal güvenlik standartları',
    'solutions.fast': 'Hızlı',
    'solutions.fast.desc': 'Milisaniye cevap süreleri',
    'solutions.scalable': 'Ölçeklenebilir',
    'solutions.scalable.desc': 'İhtiyaçlarınıza göre büyür',
    'solutions.reliable': 'Güvenilir',
    'solutions.reliable.desc': '%99.9 çalışma süresi garantisi',
    'solutions.ready-transform': 'Üretim Süreçlerinizi Dönüştürmeye Hazır mısınız?',
    'solutions.companies-transformed': '500+ şirket üretim süreçlerini bizimle optimize etti',
    'solutions.free-consultation': 'Ücretsiz Danışmanlık',
    'solutions.view-success-stories': 'Başarı Hikayelerini Görüntüle',
    
    // About Page
    'about.title': 'Hakkımızda',
    'about.subtitle': 'MES teknolojilerinde Türkiye\'nin öncü şirketi',
    'about.description': 'Üretim süreçlerini optimize etmek için gelişmiş görüntü işleme ve yapay zeka teknolojileri geliştiriyoruz.',
    'about.mission': 'Misyonumuz',
    'about.mission.desc': 'Türk sanayisini dijital dönüşümde desteklemek',
    'about.vision': 'Vizyonumuz',
    'about.vision.desc': 'Dünya standartlarında MES çözümleri sunmak',
    'about.values': 'Değerlerimiz',
    'about.values.innovation': 'İnovasyon',
    'about.values.innovation.desc': 'Sürekli yenilik ve gelişim',
    'about.values.quality': 'Kalite',
    'about.values.quality.desc': 'En yüksek kalite standartları',
    'about.values.customer': 'Müşteri Odaklılık',
    'about.values.customer.desc': 'Müşteri memnuniyeti önceliğimiz',
    'about.team': 'Ekibimiz',
    'about.team.desc': 'Alanında uzman mühendislerden oluşan ekibimiz',
    'about.experience': 'Yıl Deneyim',
    'about.projects': 'Tamamlanan Proje',
    'about.clients': 'Mutlu Müşteri',
    'about.success-rate': 'Başarı Oranı',
    
    // Sensor Analytics
    'sensor.title': 'IoT Sensör',
    'sensor.title.highlight': 'Analitik',
    'sensor.subtitle': 'Binlerce IoT sensörden gerçek zamanlı veri toplama, analiz ve görselleştirme',
    'sensor.live-dashboard': 'Canlı Sensör Paneli',
    'sensor.live-monitoring': 'Gerçek zamanlı sensör izleme',
    'sensor.connected': 'Bağlı',
    'sensor.live': 'CANLI',
    'sensor.temperature': 'Sıcaklık Sensörü',
    'sensor.humidity': 'Nem Sensörü',
    'sensor.pressure': 'Basınç Sensörü',
    'sensor.vibration': 'Titreşim Sensörü',
    'sensor.normal': 'Normal',
    'sensor.warning': 'Uyarı',
    'sensor.critical': 'Kritik',
    'sensor.trends': 'Sensör Trendleri',
    'sensor.active-alerts': 'Aktif Uyarılar',
    'sensor.high-pressure': 'Yüksek Basınç Uyarısı',
    'sensor.all-normal': 'Tüm Sistemler Normal',
    'sensor.last-check': 'Son kontrol: 30 saniye önce',
    'sensor.network-status': 'Ağ Durumu',
    'sensor.connected-sensors': 'Bağlı Sensörler',
    'sensor.data-points': 'Veri Noktaları',
    'sensor.uptime': 'Çalışma Süresi',
    'sensor.industry-apps': 'Sektörel Uygulamalar',
    'sensor.manufacturing': 'Akıllı Fabrika',
    'sensor.manufacturing.desc': 'Üretim hatları ve ekipman sağlığını gerçek zamanlı izleme',
    'sensor.smart-buildings': 'Akıllı Binalar',
    'sensor.smart-buildings.desc': 'Enerji tüketimi ve konfor optimizasyonu',
    'sensor.agriculture': 'Akıllı Tarım',
    'sensor.agriculture.desc': 'Toprak nem, pH ve hava koşulları izleme',
    'sensor.explore-solution': 'Çözümü Keşfet',
    'sensor.seamless-integration': 'Sorunsuz Entegrasyon',
    'sensor.any-sensor': 'Herhangi bir sensör, herhangi bir protokol, her yerde bağlantı',
    'sensor.wireless-protocols': 'Kablosuz Protokoller',
    'sensor.data-storage': 'Veri Depolama',
    'sensor.realtime-processing': 'Gerçek Zamanlı İşleme',
    'sensor.ai-analytics': 'AI Analitik',
    
    // Solutions
    'solutions.safety-systems': 'Güvenlik Sistemleri',
    'solutions.safety-systems.desc': 'İSG güvenliği için yapay zeka destekli çözümler',
    'solutions.automotive-quality': 'Otomotiv Kalite',
    'solutions.automotive-quality.desc': 'Araç parçalarında kalite kontrolü ve hata tespiti',
    'solutions.textile-solutions': 'Tekstil Çözümleri',
    'solutions.textile-solutions.desc': 'Kumaş kalitesi ve uzunluk ölçümü sistemleri',
    'solutions.food-safety': 'Gıda Güvenliği',
    'solutions.food-safety.desc': 'Hijyen kontrolü ve gıda güvenlik standartları',
    'solutions.manufacturing': 'İmalat Sanayi',
    'solutions.manufacturing.desc': 'Üretim hatlarında kalite kontrol ve süreç izleme',
    'solutions.energy-sector': 'Enerji Sektörü',
    'solutions.energy-sector.desc': 'Enerji tesislerinde güvenlik ve ekipman izleme',
    
    // Testimonials
    'testimonials.title': 'Müşteri',
    'testimonials.title.highlight': 'Yorumları',
    'testimonials.subtitle': 'Binlerce müşterimizin deneyimleri ve başarı hikayeleri',
    'testimonials.join-customers': 'Binlerce Mutlu Müşterimize Katılın',
    'testimonials.start-trial': '30 gün ücretsiz deneme ile başlayın, kredi kartı gerektirmez',
    'testimonials.start-free-trial': 'Ücretsiz Deneme Başlat',
    'testimonials.schedule-demo': 'Demo Planla',
    
    // Common
    'common.popular': 'Popüler',
    'common.new': 'Yeni',
    'common.accuracy': 'Doğruluk Oranı',
    'common.get-started': 'Başlayın',
    'common.learn-more': 'Daha Fazla Bilgi',
    'common.contact-us': 'İletişime Geçin',
    'common.free-demo': 'Ücretsiz Demo',
    'common.watch-demo': 'Demo İzle',
    'common.request-demo': 'Demo Talep Et',
    'common.start-trial': 'Deneme Başlat',
    'common.view-details': 'Detayları Gör',
    'common.explore': 'Keşfet',
    'common.download': 'İndir',
    'common.read-more': 'Devamını Oku',
    
    // Features
    'features.protected-workers': 'Korunan Çalışan',
    'features.active-facilities': 'Aktif Tesis',
    'features.processed-images': 'İşlenen Görüntü',
    
    // Sectors
    'sector.construction': 'İnşaat',
    'sector.construction.desc': 'Şantiye güvenliği ve kaza önleme',
    'sector.automotive': 'Otomotiv',
    'sector.automotive.desc': 'Araç parçalarında kalite kontrolü',
    'sector.textile': 'Tekstil',
    'sector.textile.desc': 'Kumaş kalitesi ve uzunluk ölçümü',
    'sector.food': 'Gıda & İçecek',
    'sector.food.desc': 'Hijyen kontrolü ve gıda güvenliği',
    'sector.manufacturing': 'İmalat',
    'sector.manufacturing.desc': 'Üretim hatlarında kalite kontrol',
    'sector.energy': 'Enerji',
    'sector.energy.desc': 'Enerji tesislerinde güvenlik izleme',
    'sector.electronics': 'Elektronik',
    'sector.electronics.desc': 'PCB ve elektronik komponent kontrolü',
    'sector.machinery': 'Makine',
    'sector.machinery.desc': 'Makine üretimi ve kalite kontrolü',
    'sector.pharmaceutical': 'İlaç',
    'sector.pharmaceutical.desc': 'İlaç üretiminde kalite ve uyumluluk',
    
    // Footer
    'footer.product': 'Ürün',
    'footer.solutions': 'Çözümler',
    'footer.resources': 'Kaynaklar',
    'footer.company': 'Şirket',
    'footer.analytics-platform': 'Analitik Platform',
    'footer.reporting-tools': 'Raporlama Araçları',
    'footer.api-documentation': 'API Dokümantasyonu',
    'footer.integrations': 'Entegrasyonlar',
    'footer.enterprise': 'Kurumsal',
    'footer.small-business': 'Küçük İşletme',
    'footer.startups': 'Startup\'lar',
    'footer.agencies': 'Ajanslar',
    'footer.ecommerce': 'E-ticaret',
    'footer.documentation': 'Dokümantasyon',
    'footer.tutorials': 'Eğitimler',
    'footer.case-studies': 'Vaka Çalışmaları',
    'footer.blog': 'Blog',
    'footer.about-us': 'Hakkımızda',
    'footer.careers': 'Kariyer',
    'footer.press': 'Basın',
    'footer.partners': 'Partnerler',
    'footer.contact': 'İletişim',
    'footer.empowering-businesses': 'İşletmeleri yapay zeka ile güçlendiriyoruz',
    'footer.stay-updated': 'Güncel Kalın',
    'footer.latest-insights': 'En son içgörüler ve güncellemeler',
    'footer.enter-email': 'E-posta adresinizi girin',
    'footer.subscribe': 'Abone Ol',
    'footer.all-rights': 'Tüm hakları saklıdır.',
    'footer.privacy-policy': 'Gizlilik Politikası',
    'footer.terms-service': 'Hizmet Şartları',
    'footer.cookie-policy': 'Çerez Politikası',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.sectors': 'Sectors',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.documentation': 'Documentation',
    'nav.support': 'Support',
    'nav.case-studies': 'Case Studies',
    'nav.resources': 'Resources',
    'nav.small-business': 'Small Business',
    'nav.medium-business': 'Medium Business',
    'nav.enterprise': 'Enterprise',
    'nav.custom-solutions': 'Custom Solutions',
    'nav.free-demo': 'Free Demo',
    
    // Pricing
    'pricing.small-business': 'Small Business',
    'pricing.medium-business': 'Medium Business',
    'pricing.enterprise': 'Enterprise',
    
    // Small Business Page
    'small-business.title': 'For Small Businesses',
    'small-business.subtitle': 'Affordable AI solutions specially designed for small businesses. Easy setup, simple usage and fast ROI to grow your business.',
    
    // Sectors
    'sectors.electronics': 'Electronics',
    'sectors.automotive': 'Automotive',
    'sectors.food-beverage': 'Food & Beverage',
    'sectors.manufacturing': 'Manufacturing',
    'sectors.machinery': 'Machinery',
    'sectors.pharmaceutical': 'Pharmaceutical',
    'sectors.textile': 'Textile',
    'sectors.energy': 'Energy',
    
    // Solutions
    'solutions.mes-api': 'MES API',
    'solutions.image-api': 'Image API',
    'solutions.process-monitoring': 'Process Monitoring',
    'solutions.production-control': 'Production Control',
    'solutions.erp-integration': 'ERP Integration',
    'solutions.sensor-analytics': 'Sensor Analytics',
    'solutions.custom-solutions': 'Custom Solutions',
    
    // Hero Section
    'hero.title': 'Optimize Your Manufacturing',
    'hero.title.highlight': 'with Computer Vision',
    'hero.subtitle': 'Monitor production lines in real-time, automate quality control, and integrate with your ERP systems using our MES (Manufacturing Execution System) solutions.',
    'hero.cta.demo': 'Free Demo',
    'hero.cta.learn': 'Learn More',
    'hero.trusted': 'Trusted by Turkey\'s leading manufacturing companies',
    
    // Features
    'features.title': 'Our MES Solutions',
    'features.subtitle': 'Advanced technologies to optimize your manufacturing processes',
    'features.production.title': 'Production Planning',
    'features.production.desc': 'Work orders, resource planning and production scheduling',
    'features.quality.title': 'Quality Management',
    'features.quality.desc': 'Automated quality control with computer vision',
    'features.process.title': 'Process Monitoring',
    'features.process.desc': 'Real-time manufacturing process monitoring',
    'features.integration.title': 'ERP Integration',
    'features.integration.desc': 'Integration with SAP, Oracle and other ERP systems',
    'features.analytics.title': 'Data Analytics',
    'features.analytics.desc': 'Production data analysis and reporting',
    'features.inventory.title': 'Inventory Management',
    'features.inventory.desc': 'Raw material and semi-finished goods tracking',
    
    // Dashboard
    'dashboard.title': 'MES Control Panel',
    'dashboard.subtitle': 'Manage your production processes from a single screen',
    'dashboard.production-lines': 'Production Lines',
    'dashboard.quality-metrics': 'Quality Metrics',
    'dashboard.efficiency': 'Efficiency',
    'dashboard.defect-rate': 'Defect Rate',
    'dashboard.throughput': 'Throughput',
    'dashboard.oee': 'OEE Score',
    'dashboard.active-orders': 'Active Orders',
    'dashboard.completed-today': 'Completed Today',
    'dashboard.pending': 'Pending',
    'dashboard.in-progress': 'In Progress',
    
    // Image Processing
    'image.title': 'Quality Control with Computer Vision',
    'image.subtitle': 'Improve production quality with AI-powered image analysis',
    'image.defect-detection': 'Defect Detection',
    'image.dimension-check': 'Dimension Check',
    'image.surface-analysis': 'Surface Analysis',
    'image.color-matching': 'Color Matching',
    
    // Solutions Page
    'solutions.title': 'Our MES',
    'solutions.title.highlight': 'Solutions',
    'solutions.subtitle': 'Comprehensive MES modules to optimize your manufacturing processes',
    'solutions.explore-solution': 'Explore Solution',
    'solutions.success-stories': 'Success Stories',
    'solutions.customer-results': 'Results achieved by our customers',
    'solutions.accident-reduction': 'Accident Reduction',
    'solutions.safety-compliance': 'Safety Compliance',
    'solutions.quality-increase': 'Quality Increase',
    'solutions.error-reduction': 'Error Reduction',
    'solutions.efficiency': 'Efficiency',
    'solutions.measurement-accuracy': 'Measurement Accuracy',
    'solutions.processing-speed': 'Processing Speed',
    'solutions.cost-savings': 'Cost Savings',
    'solutions.easy-integration': 'Easy Integration',
    'solutions.works-seamlessly': 'Works seamlessly with your existing systems',
    'solutions.secure': 'Secure',
    'solutions.secure.desc': 'Enterprise security standards',
    'solutions.fast': 'Fast',
    'solutions.fast.desc': 'Millisecond response times',
    'solutions.scalable': 'Scalable',
    'solutions.scalable.desc': 'Grows with your needs',
    'solutions.reliable': 'Reliable',
    'solutions.reliable.desc': '99.9% uptime guarantee',
    'solutions.ready-transform': 'Ready to Transform Your Manufacturing Processes?',
    'solutions.companies-transformed': '500+ companies optimized their production processes with us',
    'solutions.free-consultation': 'Free Consultation',
    'solutions.view-success-stories': 'View Success Stories',
    
    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Turkey\'s leading company in MES technologies',
    'about.description': 'We develop advanced computer vision and artificial intelligence technologies to optimize manufacturing processes.',
    'about.mission': 'Our Mission',
    'about.mission.desc': 'Supporting Turkish industry in digital transformation',
    'about.vision': 'Our Vision',
    'about.vision.desc': 'Providing world-class MES solutions',
    'about.values': 'Our Values',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.desc': 'Continuous innovation and development',
    'about.values.quality': 'Quality',
    'about.values.quality.desc': 'Highest quality standards',
    'about.values.customer': 'Customer Focus',
    'about.values.customer.desc': 'Customer satisfaction is our priority',
    'about.team': 'Our Team',
    'about.team.desc': 'Our team of expert engineers',
    'about.experience': 'Years Experience',
    'about.projects': 'Completed Projects',
    'about.clients': 'Happy Clients',
    'about.success-rate': 'Success Rate',
    
    // Sensor Analytics
    'sensor.title': 'IoT Sensor',
    'sensor.title.highlight': 'Analytics',
    'sensor.subtitle': 'Real-time data collection, analysis and visualization from thousands of IoT sensors',
    'sensor.live-dashboard': 'Live Sensor Panel',
    'sensor.live-monitoring': 'Real-time sensor monitoring',
    'sensor.connected': 'Connected',
    'sensor.live': 'LIVE',
    'sensor.temperature': 'Temperature Sensor',
    'sensor.humidity': 'Humidity Sensor',
    'sensor.pressure': 'Pressure Sensor',
    'sensor.vibration': 'Vibration Sensor',
    'sensor.normal': 'Normal',
    'sensor.warning': 'Warning',
    'sensor.critical': 'Critical',
    'sensor.trends': 'Sensor Trends',
    'sensor.active-alerts': 'Active Alerts',
    'sensor.high-pressure': 'High Pressure Warning',
    'sensor.all-normal': 'All Systems Normal',
    'sensor.last-check': 'Last check: 30 seconds ago',
    'sensor.network-status': 'Network Status',
    'sensor.connected-sensors': 'Connected Sensors',
    'sensor.data-points': 'Data Points',
    'sensor.uptime': 'Uptime',
    'sensor.industry-apps': 'Industry Applications',
    'sensor.manufacturing': 'Smart Factory',
    'sensor.manufacturing.desc': 'Real-time monitoring of production lines and equipment health',
    'sensor.smart-buildings': 'Smart Buildings',
    'sensor.smart-buildings.desc': 'Energy consumption and comfort optimization',
    'sensor.agriculture': 'Smart Agriculture',
    'sensor.agriculture.desc': 'Soil moisture, pH and weather conditions monitoring',
    'sensor.explore-solution': 'Explore Solution',
    'sensor.seamless-integration': 'Seamless Integration',
    'sensor.any-sensor': 'Any sensor, any protocol, everywhere connection',
    'sensor.wireless-protocols': 'Wireless Protocols',
    'sensor.data-storage': 'Data Storage',
    'sensor.realtime-processing': 'Real-time Processing',
    'sensor.ai-analytics': 'AI Analytics',
    
    // Solutions
    'solutions.safety-systems': 'Safety Systems',
    'solutions.safety-systems.desc': 'AI-powered solutions for occupational safety',
    'solutions.automotive-quality': 'Automotive Quality',
    'solutions.automotive-quality.desc': 'Quality control and defect detection in automotive parts',
    'solutions.textile-solutions': 'Textile Solutions',
    'solutions.textile-solutions.desc': 'Fabric quality and length measurement systems',
    'solutions.food-safety': 'Food Safety',
    'solutions.food-safety.desc': 'Hygiene control and food safety standards',
    'solutions.manufacturing': 'Manufacturing',
    'solutions.manufacturing.desc': 'Quality control and process monitoring in production lines',
    'solutions.energy-sector': 'Energy Sector',
    'solutions.energy-sector.desc': 'Safety and equipment monitoring in energy facilities',
    
    // Testimonials
    'testimonials.title': 'Customer',
    'testimonials.title.highlight': 'Reviews',
    'testimonials.subtitle': 'Experiences and success stories from thousands of our customers',
    'testimonials.join-customers': 'Join Thousands of Happy Customers',
    'testimonials.start-trial': 'Start with 30-day free trial, no credit card required',
    'testimonials.start-free-trial': 'Start Free Trial',
    'testimonials.schedule-demo': 'Schedule Demo',
    
    // Common
    'common.popular': 'Popular',
    'common.new': 'New',
    'common.accuracy': 'Accuracy Rate',
    'common.get-started': 'Get Started',
    'common.learn-more': 'Learn More',
    'common.contact-us': 'Contact Us',
    'common.free-demo': 'Free Demo',
    'common.watch-demo': 'Watch Demo',
    'common.request-demo': 'Request Demo',
    'common.start-trial': 'Start Trial',
    'common.view-details': 'View Details',
    'common.explore': 'Explore',
    'common.download': 'Download',
    'common.read-more': 'Read More',
    
    // Features
    'features.protected-workers': 'Protected Workers',
    'features.active-facilities': 'Active Facilities',
    'features.processed-images': 'Processed Images',
    
    // Sectors
    'sector.construction': 'Construction',
    'sector.construction.desc': 'Construction site safety and accident prevention',
    'sector.automotive': 'Automotive',
    'sector.automotive.desc': 'Quality control in automotive parts',
    'sector.textile': 'Textile',
    'sector.textile.desc': 'Fabric quality and length measurement',
    'sector.food': 'Food & Beverage',
    'sector.food.desc': 'Hygiene control and food safety',
    'sector.manufacturing': 'Manufacturing',
    'sector.manufacturing.desc': 'Quality control in production lines',
    'sector.energy': 'Energy',
    'sector.energy.desc': 'Safety monitoring in energy facilities',
    'sector.electronics': 'Electronics',
    'sector.electronics.desc': 'PCB and electronic component control',
    'sector.machinery': 'Machinery',
    'sector.machinery.desc': 'Machine manufacturing and quality control',
    'sector.pharmaceutical': 'Pharmaceutical',
    'sector.pharmaceutical.desc': 'Quality and compliance in drug manufacturing',
    
    // Footer
    'footer.product': 'Product',
    'footer.solutions': 'Solutions',
    'footer.resources': 'Resources',
    'footer.company': 'Company',
    'footer.analytics-platform': 'Analytics Platform',
    'footer.reporting-tools': 'Reporting Tools',
    'footer.api-documentation': 'API Documentation',
    'footer.integrations': 'Integrations',
    'footer.enterprise': 'Enterprise',
    'footer.small-business': 'Small Business',
    'footer.startups': 'Startups',
    'footer.agencies': 'Agencies',
    'footer.ecommerce': 'E-commerce',
    'footer.documentation': 'Documentation',
    'footer.tutorials': 'Tutorials',
    'footer.case-studies': 'Case Studies',
    'footer.blog': 'Blog',
    'footer.about-us': 'About Us',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.partners': 'Partners',
    'footer.contact': 'Contact',
    'footer.empowering-businesses': 'Empowering businesses with artificial intelligence',
    'footer.stay-updated': 'Stay Updated',
    'footer.latest-insights': 'Latest insights and updates',
    'footer.enter-email': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.all-rights': 'All rights reserved.',
    'footer.privacy-policy': 'Privacy Policy',
    'footer.terms-service': 'Terms of Service',
    'footer.cookie-policy': 'Cookie Policy',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'tr' | 'en'>('tr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};